name: Packaging

on: [push]
jobs:
  create-plugin-package:
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt dev tools
        run: |
          sudo apt update
          sudo apt install -y qttools5-dev-tools

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Compile translations
        run: |
          lrelease dmpcatalogue/i18n/*.ts

      - name: Collect files for packaging
        run: |
          cp LICENSE dmpcatalogue/
          rsync -av --exclude='*.pro' --exclude='*.ts' --exclude='tests' dmpcatalogue output
          (cd output && zip -9 -r ../dmpcatalogue.zip dmpcatalogue/)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dmpcatalogue
          path: output/

      - name: Upload asset on tagged release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dmpcatalogue.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
