name: Run Tests

on:
  push:
    paths:
    - "dmpcatalogue/**"
    - ".github/workflows/run_tests.yaml"
  pull_request:
    types: [opened, synchronize, edited]

env:
  PLUGIN_NAME: dmpcatalogue
  DOCKER_IMAGE: qgis/qgis

concurrency:
  group: ${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  run_plugin_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker_tags: [release-3_22, release-3_28, latest]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker pull and create qgis-testing-environment
        run: |
          docker pull "$DOCKER_IMAGE":${{ matrix.docker_tags }}
          docker run -d --name qgis-testing-environment -v "$GITHUB_WORKSPACE":/tests_directory -e DISPLAY=:99 "$DOCKER_IMAGE":${{ matrix.docker_tags }}
          # Wait for xvfb to finish starting
          printf "Waiting for the docker...🐳..."
          sleep 60
          echo " done 🥩"

      - name: Docker set up QGIS
        run: |
          docker exec qgis-testing-environment sh -c "qgis_setup.sh $PLUGIN_NAME"
          docker exec qgis-testing-environment sh -c "rm -f /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/$PLUGIN_NAME"
          docker exec qgis-testing-environment sh -c "ln -s /tests_directory/$PLUGIN_NAME /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/$PLUGIN_NAME"

      - name: Docker run plugin tests
        run: |
          docker exec qgis-testing-environment sh -c "cd /tests_directory/$PLUGIN_NAME/tests && qgis_testrunner.sh suite.test_all"
